name : Test & Deploy

on:
  push:
    branches:
      -main
  pull request:
    branches: 
      -main  
      
jobs:
  build:
    runs-on:ubuntu-latest

    steps:
     - User: actions/checkout@v3
     - name: Set up Node.js
      uses: action/Set up Node.js@v3
      with:
         node - versions: '22'
         cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: run Tests
        run: npm test

      - name:  Build and Deploy
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
